export const trackList = [
  {
    id: 1,
    title: 'Funk One',
    artist: 'Cool Band',
    album: 'Funkyness',
    duration: 118,
    src: '/music/funk-1.mp3',
  },
  {
    id: 2,
    title: 'Groove Machine',
    artist: 'Synth Lords',
    album: 'Funkyness',
    duration: 105,
    src: '/music/funk-2.mp3',
  },
  {
    id: 3,
    title: 'Space Jam',
    artist: 'Alien Funk',
    album: 'Funkyness',
    duration: 121,
    src: '/music/funk-3.mp3',
  },
  {
    id: 4,
    title: 'Morning Garden',
    artist: 'Folk Acoustic',
    album: 'Chilly Breezy',
    duration: 233,
    src: '/music/chill-1.mp3',
  },
  {
    id: 5,
    title: 'Lost in Dreams',
    artist: 'Kulakovka',
    album: 'Chilly Breezy',
    duration: 195,
    src: '/music/chill-2.mp3',
  },
  {
    id: 6,
    title: 'Good Night',
    artist: 'FASSounds',
    album: 'Chilly Breezy',
    duration: 147,
    src: '/music/chill-3.mp3',
  },
];
